Detección y Segmentación con YOLO (Transfer Learning)_COCO

**Instructor:** Dr Mario Iván López Valdovinos  
**Alumno:** Cesar Eduardo Inda Ceniceros  



    Es proyecto implementa y evalúa dos modelos de red neuronal (YOLOv8) mediante **transfer learning** a partir de pesos preentrenados en COCO, para las tareas de:

    1. **Detección de objetos** (bounding boxes)
    2. **Segmentación de instancias** (máscaras a nivel de píxel)

    Se evalúa el desempeño con las métricas estándar: Precision, Recall, F1-score, IoU, Dice y mAP (en los umbrales 0.50 y 0.50:0.95).

    **Dataset:** se utiliza `coco128-seg`, un subconjunto oficial de 128 imágenes tomadas de COCO train2017, que ya incluye anotaciones de segmentación (polígonos) además de bounding boxes. Este subconjunto es distribuido por Ultralytics específicamente para validar pipelines de entrenamiento/transfer learning sin necesitar los ~20 GB del dataset COCO completo.

    > Nota metodológica: dado que el ejercicio pide explícitamente *transfer learning* (no entrenamiento desde cero), partimos siempre de los pesos `yolov8s.pt` / `yolov8s-seg.pt` preentrenados en el COCO completo (80 clases), y hacemos fine-tuning sobre nuestra partición.

## 1. Instalación de librerías

Instalamos PyTorch (con soporte CUDA), Ultralytics YOLO, y las utilerías necesarias para manejo de datos, métricas y visualización.

In [1]:
# Si ya tienes PyTorch con CUDA instalado (recomendado, para no reinstalar torch),
# comenta la línea de torch y deja solo el resto.
!pip install ultralytics matplotlib pycocotools scikit-learn seaborn opencv-python --quiet

import ultralytics
ultralytics.checks()  # imprime versión, disponibilidad de CUDA, GPU detectada, etc.

Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
Setup complete  (12 CPUs, 15.9 GB RAM, 432.7/465.1 GB disk)

In [2]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA disponible: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM total: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
DEVICE = 0 if torch.cuda.is_available() else "cpu"

PyTorch version: 2.12.1+cpu
CUDA disponible: False

## 2. Descarga del dataset COCO (subconjunto)

Usamos `coco128-seg.zip`, distribuido oficialmente por Ultralytics. Ya viene en formato YOLO (imágenes + labels `.txt` con polígonos normalizados), lo cual nos ahorra el paso de convertir las anotaciones originales de COCO (formato JSON estilo COCO API) a formato YOLO.

Estructura que se descarga:
```
coco128-seg/
├── images/train2017/   (128 imágenes)
└── labels/train2017/   (128 archivos .txt, uno por imagen, con polígonos de segmentación)
```

Como el dataset original solo trae una partición (`train2017`), en la sección 3 lo re-particionamos nosotros mismos en 70/15/15 como pide el laboratorio.

In [3]:
import os
from pathlib import Path
from ultralytics.utils.downloads import download

DATA_ROOT = Path("./dataset_coco")
DATA_ROOT.mkdir(exist_ok=True)

# Descarga oficial del subconjunto (imágenes + labels de segmentación en formato YOLO)
url = "https://github.com/ultralytics/assets/releases/download/v0.0.0/coco128-seg.zip"
download(url, dir=DATA_ROOT, unzip=True, delete=True)

IMAGES_DIR = DATA_ROOT / "coco128-seg" / "images" / "train2017"
LABELS_DIR = DATA_ROOT / "coco128-seg" / "labels" / "train2017"

print(f"Imágenes descargadas: {len(list(IMAGES_DIR.glob('*.jpg')))}")
print(f"Labels descargados:   {len(list(LABELS_DIR.glob('*.txt')))}")

Downloading https://ultralytics.com/assets/coco128-seg.zip to 'dataset_coco\coco128-seg.zip': 100% ━━━━━━━━━━━━ 6.8MB 10.5MB/s 0.6s.6s<0.0s8s
WARNING Skipping dataset_coco\coco128-seg.zip unzip as destination directory C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\coco128-seg is not empty.
Imágenes descargadas: 128
Labels descargados:   128

In [4]:
# Nombres de las 80 clases de COCO (mismo orden que usan los pesos preentrenados de YOLO)
COCO_CLASSES = ultralytics.YOLO("yolov8s.pt").names  # dict {id: nombre}
print(f"Número de clases COCO: {len(COCO_CLASSES)}")
list(COCO_CLASSES.items())[:10]

Número de clases COCO: 80

[(0, 'person'),
 (1, 'bicycle'),
 (2, 'car'),
 (3, 'motorcycle'),
 (4, 'airplane'),
 (5, 'bus'),
 (6, 'train'),
 (7, 'truck'),
 (8, 'boat'),
 (9, 'traffic light')]

## 3. Partición del dataset (70% train / 15% val / 15% test)

Reorganizamos las 128 imágenes descargadas en tres particiones independientes, manteniendo la correspondencia imagen–etiqueta. Usamos una semilla fija para que la partición sea reproducible.

In [5]:
import random
import shutil

random.seed(42)

SPLIT_ROOT = Path("./dataset_coco/split")
if SPLIT_ROOT.exists():
    shutil.rmtree(SPLIT_ROOT)

all_images = sorted(IMAGES_DIR.glob("*.jpg"))
random.shuffle(all_images)

n_total = len(all_images)
n_train = int(n_total * 0.70)
n_val = int(n_total * 0.15)
# el resto (15% o el residuo por redondeo) va a test
splits = {
    "train": all_images[:n_train],
    "val": all_images[n_train:n_train + n_val],
    "test": all_images[n_train + n_val:],
}

for split_name, img_list in splits.items():
    img_out = SPLIT_ROOT / "images" / split_name
    lbl_out = SPLIT_ROOT / "labels" / split_name
    img_out.mkdir(parents=True, exist_ok=True)
    lbl_out.mkdir(parents=True, exist_ok=True)
    for img_path in img_list:
        label_path = LABELS_DIR / (img_path.stem + ".txt")
        shutil.copy(img_path, img_out / img_path.name)
        if label_path.exists():
            shutil.copy(label_path, lbl_out / label_path.name)

print(f"Total de imágenes: {n_total}")
for split_name, img_list in splits.items():
    pct = len(img_list) / n_total * 100
    print(f"  {split_name:5s}: {len(img_list):4d} imágenes ({pct:.1f}%)")

Total de imágenes: 128
  train:   89 imágenes (69.5%)
  val  :   19 imágenes (14.8%)
  test :   20 imágenes (15.6%)

## 4. Preparación de las anotaciones

Ultralytics YOLO usa un único formato de archivo de texto por imagen, pero el **contenido** de cada línea cambia según la tarea:

**Detección** (bounding box) — cada línea:
```
<clase> <x_centro> <y_centro> <ancho> <alto>
```
Todas las coordenadas normalizadas entre 0 y 1 respecto al tamaño de la imagen.

**Segmentación** (máscara) — cada línea:
```
<clase> <x1> <y1> <x2> <y2> ... <xn> <yn>
```
Es decir, el polígono completo del contorno del objeto, también normalizado.

`coco128-seg` ya trae las anotaciones en formato de **polígono** (segmentación). Para la tarea de **detección** derivamos el bounding box de cada objeto calculando el rectángulo delimitador (mínimo y máximo en x, y) de su polígono — así generamos las etiquetas de detección a partir de las de segmentación, garantizando que ambas tareas usen exactamente los mismos objetos.

In [6]:
def polygon_to_bbox(coords):
    """Convierte una lista plana [x1,y1,x2,y2,...] normalizada a un bbox
    YOLO [x_centro, y_centro, ancho, alto], también normalizado."""
    xs = coords[0::2]
    ys = coords[1::2]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)
    x_center = (x_min + x_max) / 2
    y_center = (y_min + y_max) / 2
    width = x_max - x_min
    height = y_max - y_min
    return x_center, y_center, width, height


def build_detection_labels(seg_labels_dir: Path, det_labels_dir: Path):
    det_labels_dir.mkdir(parents=True, exist_ok=True)
    for seg_file in seg_labels_dir.glob("*.txt"):
        lines_out = []
        with open(seg_file) as f:
            for line in f:
                parts = line.strip().split()
                if not parts:
                    continue
                cls = parts[0]
                coords = list(map(float, parts[1:]))
                xc, yc, w, h = polygon_to_bbox(coords)
                lines_out.append(f"{cls} {xc:.6f} {yc:.6f} {w:.6f} {h:.6f}")
        with open(det_labels_dir / seg_file.name, "w") as f:
            f.write("\n".join(lines_out))


# Generamos labels de detección (bbox) a partir de los labels de segmentación,
# para cada partición train/val/test
for split_name in ["train", "val", "test"]:
    seg_dir = SPLIT_ROOT / "labels" / split_name
    det_dir = SPLIT_ROOT / "labels_det" / split_name
    build_detection_labels(seg_dir, det_dir)
    print(f"Labels de detección generados para '{split_name}': "
          f"{len(list(det_dir.glob('*.txt')))} archivos")

Labels de detección generados para 'train': 87 archivos
Labels de detección generados para 'val': 19 archivos
Labels de detección generados para 'test': 20 archivos

## 5. Archivos de configuración del dataset

YOLO necesita un archivo `.yaml` que indique dónde están las imágenes de cada partición y el listado de clases. Creamos **dos** archivos: uno para detección (apunta a `labels_det/`) y otro para segmentación (apunta a `labels/`, que ya contiene los polígonos).

In [7]:
import yaml

names_dict = {i: name for i, name in COCO_CLASSES.items()}

def write_yaml(path, labels_subdir):
    cfg = {
        "path": str(SPLIT_ROOT.resolve()),
        "train": f"images/train",
        "val": f"images/val",
        "test": f"images/test",
        "names": names_dict,
    }
    with open(path, "w") as f:
        yaml.dump(cfg, f, sort_keys=False, allow_unicode=True)

# NOTA: Ultralytics infiere la carpeta de labels reemplazando "images" por "labels"
# en la ruta. Como tenemos dos variantes de labels (labels/ y labels_det/), creamos
# una copia de la estructura de imágenes apuntando a la carpeta de labels correcta
# mediante symlinks, para no duplicar las imágenes en disco.

def make_task_root(task_labels_dirname, task_root_name):
    task_root = Path(f"./dataset_coco/{task_root_name}")
    for split_name in ["train", "val", "test"]:
        img_src = (SPLIT_ROOT / "images" / split_name).resolve()
        lbl_src = (SPLIT_ROOT / task_labels_dirname / split_name).resolve()
        img_dst = task_root / "images" / split_name
        lbl_dst = task_root / "labels" / split_name
        img_dst.parent.mkdir(parents=True, exist_ok=True)
        lbl_dst.parent.mkdir(parents=True, exist_ok=True)
        if img_dst.exists() or img_dst.is_symlink():
            img_dst.unlink()
        if lbl_dst.exists() or lbl_dst.is_symlink():
            lbl_dst.unlink()
        img_dst.symlink_to(img_src)
        lbl_dst.symlink_to(lbl_src)
    return task_root

DET_ROOT = make_task_root("labels_det", "det_task")
SEG_ROOT = make_task_root("labels", "seg_task")

def write_task_yaml(path, task_root):
    cfg = {
        "path": str(task_root.resolve()),
        "train": "images/train",
        "val": "images/val",
        "test": "images/test",
        "names": names_dict,
    }
    with open(path, "w") as f:
        yaml.dump(cfg, f, sort_keys=False, allow_unicode=True)

write_task_yaml("coco_det.yaml", DET_ROOT)
write_task_yaml("coco_seg.yaml", SEG_ROOT)

print("coco_det.yaml y coco_seg.yaml generados.")

coco_det.yaml y coco_seg.yaml generados.

## 6. Modelo de detección YOLO preentrenado

Cargamos `yolov8s.pt`, un modelo YOLOv8 **small** ya preentrenado en el dataset COCO completo (80 clases). Elegimos la variante *small* como punto medio entre velocidad y precisión, apropiado para una GPU de 8GB (RTX 4060).

In [8]:
from ultralytics import YOLO

model_det = YOLO("yolov8s.pt")  # pesos preentrenados en COCO (transfer learning)
print(model_det.info())

YOLOv8s summary: 129 layers, 11,166,560 parameters, 0 gradients, 28.8 GFLOPs
(129, 11166560, 0, 28.8119296)

## 7. Entrenamiento del modelo de detección (transfer learning)

En lugar de entrenar desde cero, partimos de los pesos preentrenados (`yolov8s.pt`) y hacemos *fine-tuning* sobre nuestra partición de `coco_det.yaml`. Al arrancar desde pesos ya entrenados en COCO, el modelo converge en pocas épocas.

Parámetros elegidos para una RTX 4060 (8GB VRAM):
- `imgsz=640` (resolución estándar de YOLO)
- `batch=16` (cabe cómodamente en 8GB con yolov8s a 640px; bajar a 8 si hay error de memoria)
- `epochs=30` (suficiente para fine-tuning sobre un subconjunto pequeño; subir si se usa un dataset más grande)

In [9]:
results_det = model_det.train(
    data="coco_det.yaml",
    epochs=30,
    imgsz=640,
    batch=16,
    device=DEVICE,
    project="runs_lab",
    name="coco_det_transfer",
    pretrained=True,   # asegura que se use transfer learning, no entrenamiento desde cero
    exist_ok=True,
)

Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco_det.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=coco_det_transfer, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_lab, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to 'C:\Users\tiori\AppData\Roaming\Ultralytics\Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 2.8MB/s 0.3s 0.2s<0.1s

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2147008  ultralytics.nn.modules.head.Detect           [80, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,166,560 parameters, 11,166,544 gradients, 28.8 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
WARNING train: Slow image access detected (ping: 0.10.0 ms, read: 5.52.7 MB/s, size: 47.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\train... 87 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 89/89 212.6it/s 0.4s0.3s
train: New cache created: C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\train.cache
WARNING val: Slow image access detected (ping: 0.20.1 ms, read: 3.11.6 MB/s, size: 60.1 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\val... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19 268.5it/s 0.1s
val: New cache created: C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30         0G      1.018      1.013      1.085        151        640: 100% ━━━━━━━━━━━━ 6/6 26.1s/it 2:3628.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 12.4s/it 12.4s
                   all         19         85      0.725      0.787      0.855       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30         0G      1.023      1.023      1.098        121        640: 100% ━━━━━━━━━━━━ 6/6 18.2s/it 1:4918.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.6s/it 9.6s
                   all         19         85      0.679      0.814      0.855      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30         0G     0.9719     0.9326      1.046        138        640: 100% ━━━━━━━━━━━━ 6/6 16.0s/it 1:3616.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.4s/it 7.4s
                   all         19         85      0.767      0.734      0.845      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30         0G     0.9723     0.8663      1.052        141        640: 100% ━━━━━━━━━━━━ 6/6 16.8s/it 1:4117.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.8s/it 7.8s
                   all         19         85      0.883      0.697      0.843      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30         0G     0.9877     0.8692      1.027        160        640: 100% ━━━━━━━━━━━━ 6/6 17.3s/it 1:4418.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.7s/it 7.7s
                   all         19         85      0.751      0.753      0.837      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30         0G     0.8861     0.8124      1.036        127        640: 100% ━━━━━━━━━━━━ 6/6 17.4s/it 1:4418.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.9s/it 7.9s
                   all         19         85      0.832      0.721      0.838      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30         0G     0.9851     0.8378      1.068        136        640: 100% ━━━━━━━━━━━━ 6/6 17.1s/it 1:4317.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.4s/it 7.4s
                   all         19         85      0.818      0.723      0.827      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30         0G     0.9239     0.7946      1.023        162        640: 100% ━━━━━━━━━━━━ 6/6 17.1s/it 1:4317.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.3s/it 7.3s
                   all         19         85      0.832      0.711      0.813      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30         0G     0.9056     0.7431      1.015        103        640: 100% ━━━━━━━━━━━━ 6/6 17.2s/it 1:4317.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.4s/it 7.4s
                   all         19         85      0.816      0.711      0.809      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30         0G     0.9042     0.7626      1.025        117        640: 100% ━━━━━━━━━━━━ 6/6 18.6s/it 1:5220.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.5s/it 8.5s
                   all         19         85      0.813      0.699      0.809       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30         0G     0.8771     0.7509      1.032         82        640: 100% ━━━━━━━━━━━━ 6/6 18.6s/it 1:5219.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.1s/it 8.1s
                   all         19         85      0.825      0.694      0.807      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30         0G     0.8777     0.7194      1.027        125        640: 100% ━━━━━━━━━━━━ 6/6 18.1s/it 1:4918.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.6s/it 7.6s
                   all         19         85      0.805       0.68      0.803      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30         0G     0.8628     0.7162     0.9995        148        640: 100% ━━━━━━━━━━━━ 6/6 17.7s/it 1:4619.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.5s/it 8.5s
                   all         19         85      0.696      0.715      0.799      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30         0G     0.9099     0.7002      1.025        153        640: 100% ━━━━━━━━━━━━ 6/6 17.1s/it 1:4317.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.3s/it 7.3s
                   all         19         85      0.633       0.72      0.801      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30         0G     0.8542      0.706      1.023        149        640: 100% ━━━━━━━━━━━━ 6/6 17.1s/it 1:4217.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.9s/it 7.9s
                   all         19         85       0.58      0.773      0.805      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30         0G     0.8609     0.7092     0.9913        252        640: 100% ━━━━━━━━━━━━ 6/6 16.9s/it 1:4117.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.3s/it 7.3s
                   all         19         85      0.569      0.785      0.812      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30         0G      0.793     0.6687     0.9873        212        640: 100% ━━━━━━━━━━━━ 6/6 16.6s/it 1:4017.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.3s/it 7.3s
                   all         19         85      0.569      0.777      0.801      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30         0G     0.7986     0.6664      1.009        147        640: 100% ━━━━━━━━━━━━ 6/6 16.8s/it 1:4117.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.1s/it 8.1s
                   all         19         85      0.582      0.784      0.803      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30         0G      0.843     0.6637     0.9965        239        640: 100% ━━━━━━━━━━━━ 6/6 17.7s/it 1:4620.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.8s/it 9.8s
                   all         19         85      0.596      0.773        0.8      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30         0G     0.8122     0.6222     0.9905        115        640: 100% ━━━━━━━━━━━━ 6/6 16.5s/it 1:3917.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.6s/it 7.6s
                   all         19         85      0.614      0.768      0.801      0.622
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30         0G     0.9407      0.854      1.035         42        640: 100% ━━━━━━━━━━━━ 6/6 16.1s/it 1:3616.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.4s/it 7.4s
                   all         19         85      0.661      0.777      0.804      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30         0G     0.9027     0.8018      1.014         75        640: 100% ━━━━━━━━━━━━ 6/6 15.7s/it 1:3415.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.8s/it 6.8s
                   all         19         85      0.667      0.771      0.809      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30         0G     0.8958     0.7837      1.014         45        640: 100% ━━━━━━━━━━━━ 6/6 15.8s/it 1:3516.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.0s/it 7.0s
                   all         19         85      0.675      0.764      0.805      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30         0G     0.9012     0.6962      1.026         77        640: 100% ━━━━━━━━━━━━ 6/6 15.8s/it 1:3516.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.1s/it 7.1s
                   all         19         85      0.708      0.726      0.792      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30         0G      0.875     0.6635      0.988         93        640: 100% ━━━━━━━━━━━━ 6/6 15.7s/it 1:3416.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.3s/it 8.3s
                   all         19         85      0.706      0.726      0.793      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30         0G     0.9058     0.7402     0.9677         42        640: 100% ━━━━━━━━━━━━ 6/6 17.8s/it 1:4716.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.5s/it 7.5s
                   all         19         85      0.709      0.723       0.79      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30         0G     0.8768     0.6309      1.016         86        640: 100% ━━━━━━━━━━━━ 6/6 15.9s/it 1:3515.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.0s/it 7.0s
                   all         19         85       0.67      0.727       0.78      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30         0G     0.8484     0.6496      1.001         68        640: 100% ━━━━━━━━━━━━ 6/6 15.9s/it 1:3616.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.8s/it 7.8s
                   all         19         85      0.694      0.721      0.785      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30         0G     0.8482     0.6342     0.9718         81        640: 100% ━━━━━━━━━━━━ 6/6 17.2s/it 1:4318.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.9s/it 9.9s
                   all         19         85      0.681      0.722      0.785      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30         0G     0.8907     0.6635     0.9848         80        640: 100% ━━━━━━━━━━━━ 6/6 18.7s/it 1:5218.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 7.9s/it 7.9s
                   all         19         85      0.658       0.73      0.785       0.61

30 epochs completed in 0.942 hours.
Optimizer stripped from C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer\weights\last.pt, 22.6MB
Optimizer stripped from C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer\weights\best.pt, 22.6MB

Validating C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer\weights\best.pt...
Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
Model summary (fused): 73 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 6.1s/it 6.1s
                   all         19         85      0.724      0.787      0.853      0.689
                person          7         14      0.885      0.857      0.891      0.708
            motorcycle          1          1      0.684          1      0.995      0.895
                 bench          1          2      0.812          1      0.995      0.438

## 8. Modelo de segmentación YOLO preentrenado

Análogamente, cargamos `yolov8s-seg.pt`, la variante de YOLOv8 preentrenada para **segmentación de instancias** sobre COCO.

**Limpieza de memoria GPU** antes de cargar el siguiente modelo (evita acumulación de VRAM entre entrenamientos sucesivos).

In [10]:
import gc

# Liberamos memoria GPU/CPU acumulada de la etapa anterior antes de cargar
# el siguiente modelo. Evita el error 'CUDA out of memory' cuando se corren
# varios entrenamientos seguidos en la misma sesión de kernel.
torch.cuda.empty_cache()
gc.collect()
if torch.cuda.is_available():
    print(f"VRAM libre: {torch.cuda.mem_get_info()[0] / 1e9:.2f} GB de "
          f"{torch.cuda.mem_get_info()[1] / 1e9:.2f} GB totales")

In [11]:
model_seg = YOLO("yolov8s-seg.pt")  # pesos preentrenados en COCO (transfer learning)
print(model_seg.info())

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8s-seg.pt to 'yolov8s-seg.pt': 100% ━━━━━━━━━━━━ 22.8MB 11.3MB/s 2.0s1.9s<0.1sss
YOLOv8s-seg summary: 151 layers, 11,821,056 parameters, 0 gradients, 40.3 GFLOPs
(151, 11821056, 0, 40.3390976)

## 9. Entrenamiento del modelo de segmentación (transfer learning)

Usamos la misma partición 70/15/15 (mismas imágenes) pero apuntando al archivo `coco_seg.yaml`, cuyas etiquetas contienen los polígonos de segmentación.

In [12]:
results_seg = model_seg.train(
    data="coco_seg.yaml",
    epochs=30,
    imgsz=640,
    batch=16,
    device=DEVICE,
    project="runs_lab",
    name="coco_seg_transfer",
    pretrained=True,
    exist_ok=True,
)

Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco_seg.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=coco_seg_transfer, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_lab, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab\coco_seg_transfer, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2801504  ultralytics.nn.modules.head.Segment          [80, 32, 128, 16, None, [128, 256, 512]]
YOLOv8s-seg summary: 152 layers, 11,821,056 parameters, 11,821,040 gradients, 40.3 GFLOPs

Transferred 417/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
train: Fast image access  (ping: 0.10.1 ms, read: 119.749.5 MB/s, size: 45.9 KB)
train: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\train.cache... 87 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 89/89  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 200.571.2 MB/s, size: 47.5 KB)
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\val.cache... 19 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 19/19  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Plotting labels to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab\coco_seg_transfer\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab\coco_seg_transfer
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       1/30         0G      1.056      2.339       1.15      1.091          0        152        640: 100% ━━━━━━━━━━━━ 6/6 28.2s/it 2:4932.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.6s/it 13.6s
                   all         19         85      0.692      0.741      0.841      0.704      0.744      0.689      0.786      0.585

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       2/30         0G      1.052      2.324      1.128      1.103          0        165        640: 100% ━━━━━━━━━━━━ 6/6 27.5s/it 2:4525.6s5
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.2s/it 11.2s
                   all         19         85      0.619      0.785      0.843      0.684       0.62      0.774      0.802      0.587

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       3/30         0G     0.9944      2.288      1.025      1.091          0        139        640: 100% ━━━━━━━━━━━━ 6/6 24.1s/it 2:2524.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.1s/it 11.1s
                   all         19         85      0.624      0.798       0.84      0.679      0.632      0.777      0.799      0.583

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       4/30         0G     0.9279      2.136     0.9249      1.063          0        101        640: 100% ━━━━━━━━━━━━ 6/6 23.8s/it 2:2324.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.8s/it 10.8s
                   all         19         85      0.624      0.794      0.827      0.663      0.627      0.785      0.803      0.566

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       5/30         0G     0.9734      2.189     0.9534      1.088          0         90        640: 100% ━━━━━━━━━━━━ 6/6 22.8s/it 2:1723.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.9s/it 10.9s
                   all         19         85      0.611      0.755      0.808      0.646      0.628      0.761      0.791      0.559

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       6/30         0G     0.9606      2.175     0.9216      1.045          0        131        640: 100% ━━━━━━━━━━━━ 6/6 23.1s/it 2:1823.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.9s/it 10.9s
                   all         19         85      0.675      0.764      0.814      0.649      0.658      0.748      0.803      0.557

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       7/30         0G     0.9348      2.129     0.9505      1.083          0         53        640: 100% ━━━━━━━━━━━━ 6/6 22.9s/it 2:1723.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.9s/it 10.9s
                   all         19         85      0.737      0.699      0.808      0.632      0.723      0.686      0.793      0.553

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       8/30         0G     0.9494      2.063     0.8785      1.035          0        131        640: 100% ━━━━━━━━━━━━ 6/6 25.4s/it 2:32.1s33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0s/it 11.0s
                   all         19         85      0.721        0.7      0.809      0.624      0.709      0.677      0.783      0.553

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       9/30         0G     0.9581      2.157     0.8171      1.048          0        137        640: 100% ━━━━━━━━━━━━ 6/6 23.4s/it 2:2023.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.7s/it 10.7s
                   all         19         85      0.697      0.701      0.806      0.625      0.676       0.68      0.782      0.546

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      10/30         0G      1.003      2.224     0.8561      1.052          0        165        640: 100% ━━━━━━━━━━━━ 6/6 23.5s/it 2:2123.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.5s/it 10.5s
                   all         19         85      0.626      0.752      0.809      0.636      0.618      0.742      0.788      0.554

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      11/30         0G     0.9347      2.094     0.8341       1.04          0        125        640: 100% ━━━━━━━━━━━━ 6/6 23.2s/it 2:1924.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.7s/it 10.7s
                   all         19         85      0.641      0.794      0.805      0.624      0.634      0.784      0.784      0.552

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      12/30         0G     0.8832      1.949     0.7686      1.016          0        124        640: 100% ━━━━━━━━━━━━ 6/6 22.8s/it 2:1723.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0s/it 11.0s
                   all         19         85      0.609      0.818      0.801      0.619      0.594      0.791      0.765      0.535

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      13/30         0G     0.9031       1.96     0.7645      1.023          0         65        640: 100% ━━━━━━━━━━━━ 6/6 24.3s/it 2:2625.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.6s/it 11.6s
                   all         19         85      0.597      0.819      0.798      0.615      0.577      0.792      0.762      0.528

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      14/30         0G      0.873      1.943     0.7468      1.015          0        142        640: 100% ━━━━━━━━━━━━ 6/6 25.0s/it 2:3024.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0s/it 11.0s
                   all         19         85      0.694      0.722      0.803      0.617      0.685       0.71      0.781      0.529

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      15/30         0G     0.9347       2.01     0.7664      1.029          0        146        640: 100% ━━━━━━━━━━━━ 6/6 23.5s/it 2:2124.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.9s/it 10.9s
                   all         19         85      0.683      0.721      0.799      0.622      0.676      0.713      0.781      0.545

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      16/30         0G     0.8294      1.853      0.768      0.996          0        151        640: 100% ━━━━━━━━━━━━ 6/6 23.5s/it 2:2125.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.2s/it 11.2s
                   all         19         85      0.629      0.733       0.79      0.619      0.626       0.73      0.778      0.546

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      17/30         0G     0.8165      1.848     0.6821     0.9845          0        147        640: 100% ━━━━━━━━━━━━ 6/6 23.6s/it 2:2223.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.2s/it 10.2s
                   all         19         85      0.605      0.754      0.792      0.623      0.602      0.749      0.781      0.543

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      18/30         0G     0.9009      1.973      0.761      1.023          0        134        640: 100% ━━━━━━━━━━━━ 6/6 23.2s/it 2:1924.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0s/it 11.0s
                   all         19         85       0.59      0.787      0.795      0.623      0.569      0.765      0.769      0.548

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      19/30         0G     0.8459      1.918     0.7157     0.9896          0        133        640: 100% ━━━━━━━━━━━━ 6/6 23.2s/it 2:1925.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.7s/it 10.7s
                   all         19         85      0.591      0.786      0.797      0.627      0.572      0.763       0.77      0.549

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      20/30         0G     0.8945      1.994     0.7301       1.01          0        184        640: 100% ━━━━━━━━━━━━ 6/6 23.1s/it 2:1923.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.5s/it 10.5s
                   all         19         85      0.649      0.708        0.8      0.628      0.627      0.683      0.771      0.541
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      21/30         0G     0.8995      1.868      0.732      1.011          0         42        640: 100% ━━━━━━━━━━━━ 6/6 22.5s/it 2:1522.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.9s/it 10.9s
                   all         19         85      0.643       0.71      0.801      0.627      0.627       0.68       0.77      0.542

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      22/30         0G     0.9216      1.954     0.8229     0.9965          0         75        640: 100% ━━━━━━━━━━━━ 6/6 24.1s/it 2:2423.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.4s/it 10.4s
                   all         19         85      0.606      0.722      0.799      0.616      0.583      0.692      0.767      0.548

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      23/30         0G      0.858      1.833     0.7161     0.9934          0         43        640: 100% ━━━━━━━━━━━━ 6/6 21.2s/it 2:0721.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.9s/it 9.9s
                   all         19         85      0.592      0.712      0.799      0.621      0.642      0.632      0.741      0.543

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      24/30         0G     0.8615      1.903     0.6821     0.9683          0         72        640: 100% ━━━━━━━━━━━━ 6/6 21.5s/it 2:0922.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.4s/it 10.4s
                   all         19         85      0.609       0.69      0.779      0.611      0.645      0.635      0.758      0.527

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      25/30         0G     0.8293       1.78     0.6543     0.9754          0         95        640: 100% ━━━━━━━━━━━━ 6/6 21.1s/it 2:0721.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.6s/it 10.6s
                   all         19         85      0.658      0.648      0.776      0.615      0.649      0.636      0.757       0.54

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      26/30         0G      0.864      1.819     0.6701     0.9925          0         47        640: 100% ━━━━━━━━━━━━ 6/6 21.0s/it 2:0621.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.6s/it 10.6s
                   all         19         85      0.672      0.647      0.774      0.622      0.654      0.624      0.746      0.539

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size

## 10. Evaluación del modelo de detección (sobre el conjunto de test)

### Ecuaciones de las métricas

**Precision** — de todo lo que el modelo predijo como positivo, ¿qué fracción era correcta?
$$Precision = \frac{TP}{TP + FP}$$

**Recall** — de todos los objetos reales, ¿qué fracción detectó el modelo?
$$Recall = \frac{TP}{TP + FN}$$

**F1-score** — media armónica entre precision y recall:
$$F1 = 2 \cdot \frac{Precision \cdot Recall}{Precision + Recall}$$

**Intersection over Union (IoU)** — mide qué tanto se traslapan la caja/máscara predicha ($A$) y la real ($B$):
$$IoU = \frac{|A \cap B|}{|A \cup B|}$$
Una predicción se cuenta como *True Positive* (TP) si su IoU respecto al ground-truth supera un umbral (por ejemplo 0.50).

**mAP@0.50** — mAP (mean Average Precision) calculado usando un único umbral de IoU = 0.50 para decidir aciertos, promediado sobre todas las clases.

**mAP@0.50:0.95** — el mismo cálculo pero promediado sobre 10 umbrales de IoU (0.50, 0.55, ..., 0.95), lo que da una medida más estricta y completa de la calidad de localización.

Donde $TP$ = verdaderos positivos, $FP$ = falsos positivos, $FN$ = falsos negativos.

In [13]:
metrics_det = model_det.val(data="coco_det.yaml", split="test", device=DEVICE)

precision_det = metrics_det.box.mp        # Precision promedio (todas las clases)
recall_det = metrics_det.box.mr           # Recall promedio
map50_det = metrics_det.box.map50         # mAP@0.50
map5095_det = metrics_det.box.map         # mAP@0.50:0.95
f1_det = (2 * precision_det * recall_det / (precision_det + recall_det)
          if (precision_det + recall_det) > 0 else 0.0)

print("=== Métricas de DETECCIÓN (test set) ===")
print(f"Precision      : {precision_det:.4f}")
print(f"Recall         : {recall_det:.4f}")
print(f"F1-score       : {f1_det:.4f}")
print(f"mAP@0.50       : {map50_det:.4f}")
print(f"mAP@0.50:0.95  : {map5095_det:.4f}")

Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
Model summary (fused): 73 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs
WARNING val: Slow image access detected (ping: 0.30.1 ms, read: 4.11.3 MB/s, size: 43.6 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\test... 20 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 20/20 301.3it/s 0.1s
val: New cache created: C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\test.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.9s/it 5.8s<15.7s
                   all         20        106       0.74      0.775      0.873      0.704
                person          9         27      0.959      0.667      0.912      0.661
               bicycle          1          2          1      0.612      0.995       0.41
                   car          2          4      0.398      0.496      0.484      0.253
            motorcycle          1          2      0.807          1      0.995      0.795
                   bus          1          1      0.518          1      0.995      0.995
                 train          1          1      0.771          1      0.995      0.895
             stop sign          1          1      0.701          1      0.995      0.796
                  bird          1          8      0.793      0.875      0.971      0.759
                   cat          1          1      0.689          1      0.995      0.895
                   dog          1          1      0.486          1      0.995      0.895
              elephant          1          7       0.93          1      0.995      0.851
                 zebra          1          1      0.685          1      0.995      0.995
              umbrella          1          1      0.694          1      0.995      0.895
               frisbee          3          3       0.66          1      0.995      0.863
           sports ball          1          1          1          0          0          0
          baseball bat          1          1          1          0      0.249      0.106
        baseball glove          1          1      0.666          1      0.995      0.895
            skateboard          1          3          1          0      0.589      0.302
         tennis racket          1          1      0.477          1      0.497      0.199
                bottle          2          3      0.592      0.667      0.585      0.556
                   cup          1          2      0.778          1      0.995       0.92
                 knife          1          5      0.896          1      0.995      0.836
                 spoon          1          1      0.623          1      0.995      0.497
                  bowl          1          1      0.413          1      0.995      0.895
                banana          1          1      0.637          1      0.995      0.995
              sandwich          1          1          1          0      0.995      0.895
                   bed          1          1       0.87          1      0.995      0.448
          dining table          2          2          1      0.985      0.995       0.72
                    tv          1          1      0.659          1      0.995      0.895
                 mouse          1          1          1          0      0.995      0.796
             microwave          1          1      0.693          1      0.995      0.895
                  oven          1          1      0.419          1      0.995      0.995
                  book          2         16      0.436     0.0625      0.525      0.269
            teddy bear          1          2      0.909          1      0.995      0.846
Speed: 4.4ms preprocess, 276.1ms inference, 0.0ms loss, 2.1ms postprocess per image
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\val
=== Métricas de DETECCIÓN (test set) ===
Precision      : 0.7400
Recall         : 0.7754
F1-score       : 0.7573
mAP@0.50       : 0.8732
mAP@0.50:0.95  : 0.7036

## 11. Evaluación del modelo de segmentación (sobre el conjunto de test)

### Coeficiente Dice

El coeficiente **Dice** (también llamado F1 a nivel de píxel) mide la similitud entre la máscara predicha ($A$) y la máscara real ($B$):

$$Dice = \frac{2 \, |A \cap B|}{|A| + |B|} = \frac{2\,TP}{2\,TP + FP + FN}$$

Se relaciona con IoU mediante: $Dice = \dfrac{2 \cdot IoU}{1 + IoU}$

Las demás métricas (Mask Precision, Mask Recall, Mask mAP@0.50, Mask mAP@0.50:0.95, IoU) se calculan igual que en detección, pero comparando **máscaras a nivel de píxel** en vez de bounding boxes.

In [14]:
metrics_seg = model_seg.val(data="coco_seg.yaml", split="test", device=DEVICE)

mask_precision = metrics_seg.seg.mp
mask_recall = metrics_seg.seg.mr
mask_map50 = metrics_seg.seg.map50
mask_map5095 = metrics_seg.seg.map

print("=== Métricas de SEGMENTACIÓN — máscaras (test set) ===")
print(f"Mask Precision     : {mask_precision:.4f}")
print(f"Mask Recall        : {mask_recall:.4f}")
print(f"Mask mAP@0.50      : {mask_map50:.4f}")
print(f"Mask mAP@0.50:0.95 : {mask_map5095:.4f}")

Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
YOLOv8s-seg summary (fused): 86 layers, 11,810,560 parameters, 0 gradients, 40.1 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 209.070.0 MB/s, size: 43.5 KB)
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\test.cache... 20 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 20/20  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.8s/it 9.6s<24.2s
                   all         20        106      0.741      0.768      0.849      0.693      0.741      0.768      0.846      0.609
                person          9         27          1      0.687      0.897      0.627          1      0.687      0.892      0.461
               bicycle          1          2      0.969          1      0.995      0.596      0.969          1      0.995       0.43
                   car          2          4      0.594      0.391        0.5      0.279      0.594      0.391      0.527      0.285
            motorcycle          1          2      0.816          1      0.995      0.795      0.816          1      0.995      0.546
                   bus          1          1       0.72          1      0.995      0.895       0.72          1      0.995      0.895
                 train          1          1      0.725          1      0.995      0.895      0.725          1      0.995      0.895
             stop sign          1          1       0.73          1      0.995      0.796       0.73          1      0.995      0.697
                  bird          1          8      0.937          1      0.995      0.738      0.937          1      0.995      0.632
                   cat          1          1       0.72          1      0.995      0.895       0.72          1      0.995      0.895
                   dog          1          1       0.62          1      0.995      0.995       0.62          1      0.995      0.895
              elephant          1          7      0.939          1      0.995      0.841      0.939          1      0.995      0.628
                 zebra          1          1      0.704          1      0.995      0.995      0.704          1      0.995      0.895
              umbrella          1          1      0.755          1      0.995      0.895      0.755          1      0.995      0.895
               frisbee          3          3      0.728          1      0.913      0.855      0.728          1      0.913      0.648
           sports ball          1          1          1          0          0          0          1          0          0          0
          baseball bat          1          1          0          0     0.0622     0.0311          0          0     0.0622     0.0249
        baseball glove          1          1      0.526          1      0.995      0.895      0.526          1      0.995      0.895
            skateboard          1          3      0.377      0.251      0.333      0.184      0.377      0.251      0.368      0.123
         tennis racket          1          1      0.848          1      0.995       0.41      0.848          1      0.995      0.468
                bottle          2          3      0.607      0.667       0.72      0.703      0.607      0.667       0.72       0.61
                   cup          1          2      0.688          1      0.995      0.995      0.688          1      0.995      0.995
                 knife          1          5      0.885          1      0.995      0.879      0.885          1      0.995      0.727
                 spoon          1          1      0.628          1      0.995      0.895      0.628          1      0.995      0.895
                  bowl          1          1      0.802          1      0.995      0.895      0.802          1      0.995      0.895
                banana          1          1      0.735          1      0.995      0.895      0.735          1      0.995      0.697
              sandwich          1          1      0.905          1      0.995      0.895      0.905          1      0.995      0.497
                   bed          1          1          1          0      0.995      0.448          1          0      0.995      0.448
          dining table          2          2       0.56        0.5      0.662       0.55       0.56        0.5      0.662      0.446
                    tv          1          1      0.682          1      0.995      0.895      0.682          1      0.995      0.895
                 mouse          1          1          1          0      0.497      0.398          1          0      0.497      0.398
             microwave          1          1      0.485          1      0.995      0.506      0.485          1      0.995      0.332
                  oven          1          1       0.52          1      0.995      0.995       0.52          1      0.995      0.995
                  book          2         16          1          0      0.386      0.199          1          0      0.237      0.109
            teddy bear          1          2          1        0.6      0.995      0.796          1        0.6      0.995      0.547
Speed: 2.9ms preprocess, 435.7ms inference, 0.0ms loss, 15.0ms postprocess per image
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\val
=== Métricas de SEGMENTACIÓN — máscaras (test set) ===
Mask Precision     : 0.7413
Mask Recall        : 0.7675
Mask mAP@0.50      : 0.8458
Mask mAP@0.50:0.95 : 0.6088

In [15]:
# IoU y Dice promedio calculados directamente sobre las predicciones del test set,
# comparando cada máscara predicha contra su máscara ground-truth correspondiente.
import numpy as np
import cv2

def mask_iou_dice(pred_mask: np.ndarray, gt_mask: np.ndarray):
    """pred_mask y gt_mask son arreglos binarios (0/1) del mismo tamaño."""
    intersection = np.logical_and(pred_mask, gt_mask).sum()
    union = np.logical_or(pred_mask, gt_mask).sum()
    iou = intersection / union if union > 0 else 0.0
    dice = (2 * intersection) / (pred_mask.sum() + gt_mask.sum()) \
        if (pred_mask.sum() + gt_mask.sum()) > 0 else 0.0
    return iou, dice


test_images_seg = sorted((SEG_ROOT / "images" / "test").glob("*.jpg"))
iou_scores, dice_scores = [], []

for img_path in test_images_seg:
    result = model_seg.predict(source=str(img_path), device=DEVICE, verbose=False)[0]
    label_path = SEG_ROOT / "labels" / "test" / (img_path.stem + ".txt")
    if result.masks is None or not label_path.exists():
        continue

    h, w = result.orig_shape
    # Máscara ground-truth: reconstruimos el polígono normalizado del archivo .txt
    gt_mask = np.zeros((h, w), dtype=np.uint8)
    with open(label_path) as f:
        for line in f:
            parts = line.strip().split()
            coords = list(map(float, parts[1:]))
            pts = np.array(coords, dtype=np.float32).reshape(-1, 2)
            pts[:, 0] *= w
            pts[:, 1] *= h
            cv2.fillPoly(gt_mask, [pts.astype(np.int32)], 1)

    # Combinamos todas las máscaras predichas en una sola máscara binaria
    pred_mask = result.masks.data.cpu().numpy().sum(axis=0)
    pred_mask = (pred_mask > 0).astype(np.uint8)
    pred_mask = cv2.resize(pred_mask, (w, h), interpolation=cv2.INTER_NEAREST)

    iou, dice = mask_iou_dice(pred_mask, gt_mask)
    iou_scores.append(iou)
    dice_scores.append(dice)

mean_iou = float(np.mean(iou_scores)) if iou_scores else 0.0
mean_dice = float(np.mean(dice_scores)) if dice_scores else 0.0

print(f"IoU promedio (test)  : {mean_iou:.4f}")
print(f"Dice promedio (test) : {mean_dice:.4f}")

IoU promedio (test)  : 0.8013
Dice promedio (test) : 0.8845

### Resumen de todas las métricas requeridas

In [16]:
import pandas as pd

summary = pd.DataFrame({
    "Métrica": [
        "Precision (det)", "Recall (det)", "F1-score (det)",
        "mAP@0.50 (det)", "mAP@0.50:0.95 (det)",
        "Mask Precision", "Mask Recall",
        "Mask mAP@0.50", "Mask mAP@0.50:0.95",
        "IoU", "Dice",
    ],
    "Valor": [
        precision_det, recall_det, f1_det, map50_det, map5095_det,
        mask_precision, mask_recall, mask_map50, mask_map5095,
        mean_iou, mean_dice,
    ],
})
summary["Valor"] = summary["Valor"].round(4)
summary

                Métrica   Valor
0       Precision (det)  0.7400
1          Recall (det)  0.7754
2        F1-score (det)  0.7573
3        mAP@0.50 (det)  0.8732
4   mAP@0.50:0.95 (det)  0.7036
5        Mask Precision  0.7413
6           Mask Recall  0.7675
7         Mask mAP@0.50  0.8458
8    Mask mAP@0.50:0.95  0.6088
9                   IoU  0.8013
10                 Dice  0.8845

## 12. Visualización de resultados

Para varias imágenes del conjunto de test mostramos, en una sola figura:

1. Imagen original con anotaciones **ground-truth** (caja + máscara real)
2. Predicción del modelo de **detección** (cajas + score de confianza)
3. Predicción del modelo de **segmentación** (máscaras + score de confianza)

In [17]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches

def draw_gt(ax, img_path, seg_root):
    img = cv2.cvtColor(cv2.imread(str(img_path)), cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]
    ax.imshow(img)
    label_path = seg_root / "labels" / "test" / (img_path.stem + ".txt")
    if label_path.exists():
        with open(label_path) as f:
            for line in f:
                parts = line.strip().split()
                cls_id = int(parts[0])
                coords = list(map(float, parts[1:]))
                pts = np.array(coords).reshape(-1, 2)
                pts[:, 0] *= w
                pts[:, 1] *= h
                poly = patches.Polygon(pts, closed=True, fill=False,
                                        edgecolor="lime", linewidth=2)
                ax.add_patch(poly)
                ax.text(pts[:, 0].min(), pts[:, 1].min() - 4,
                        COCO_CLASSES[cls_id], color="lime", fontsize=8,
                        backgroundcolor="black")
    ax.set_title("Ground truth")
    ax.axis("off")


def draw_detection(ax, img_path):
    result = model_det.predict(source=str(img_path), device=DEVICE, verbose=False)[0]
    img = cv2.cvtColor(cv2.imread(str(img_path)), cv2.COLOR_BGR2RGB)
    ax.imshow(img)
    for box in result.boxes:
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        conf = float(box.conf[0])
        cls_id = int(box.cls[0])
        rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1,
                                  fill=False, edgecolor="red", linewidth=2)
        ax.add_patch(rect)
        ax.text(x1, y1 - 4, f"{COCO_CLASSES[cls_id]} {conf:.2f}",
                color="red", fontsize=8, backgroundcolor="black")
    ax.set_title("Detección (predicción)")
    ax.axis("off")


def draw_segmentation(ax, img_path):
    result = model_seg.predict(source=str(img_path), device=DEVICE, verbose=False)[0]
    ax.imshow(result.plot(boxes=False)[:, :, ::-1])  # plot() dibuja máscaras + conf
    ax.set_title("Segmentación (predicción)")
    ax.axis("off")


N_EXAMPLES = 4
sample_imgs = test_images_seg[:N_EXAMPLES]

fig, axes = plt.subplots(N_EXAMPLES, 3, figsize=(15, 5 * N_EXAMPLES))
for i, img_path in enumerate(sample_imgs):
    draw_gt(axes[i, 0], img_path, SEG_ROOT)
    draw_detection(axes[i, 1], img_path)
    draw_segmentation(axes[i, 2], img_path)

plt.tight_layout()
plt.savefig("resultados_visualizacion.png", dpi=150, bbox_inches="tight")
plt.show()

## 13. Conclusiones

- Se aplicó **transfer learning** partiendo de los pesos `yolov8s.pt` / `yolov8s-seg.pt` (preentrenados en COCO), en vez de entrenar desde cero, tal como se solicitó.
- El dataset se particionó en 70% train / 15% val / 15% test de forma reproducible (semilla fija).
- Las anotaciones de detección se derivaron automáticamente de las de segmentación, garantizando consistencia entre ambas tareas sobre el mismo conjunto de objetos.
- Se reportaron todas las métricas solicitadas: Precision, Recall, F1, mAP@0.50, mAP@0.50:0.95 (detección) y Mask Precision, Mask Recall, Mask mAP@0.50, Mask mAP@0.50:0.95, IoU, Dice (segmentación).
- La visualización final compara, imagen por imagen, el ground-truth contra las predicciones de ambos modelos, incluyendo los scores de confianza.

---

## 14. Extensión opcional — escalando el laboratorio (dataset completo + modelo más grande)

Todo lo anterior (secciones 1-13) cumple los requisitos mínimos del laboratorio usando `coco128-seg` (128 imágenes) y `yolov8s`. Esta sección es una **extensión adicional**: se repite el mismo pipeline de transfer learning, pero escalado a:

- **Dataset:** COCO val2017 completo (**5,000 imágenes reales**, con las 80 clases de COCO bien representadas — no solo 1-2 instancias por clase como en el subconjunto de 128).
- **Modelo:** `yolov8m` / `yolov8m-seg` (medium, ~26M parámetros, vs. los ~11M de `yolov8s`).
- **Épocas:** 80, con `patience=15` (se detiene automáticamente si no mejora en 15 épocas seguidas, para no desperdiciar tiempo de GPU).

Se reutilizan las mismas funciones ya definidas arriba (`polygon_to_bbox`, `build_detection_labels`, `make_task_root`, `write_task_yaml`), aplicadas ahora sobre el dataset completo.

> ⚠️ Este entrenamiento es considerablemente más pesado. Con una RTX 4060 (8GB) y 16 núcleos de CPU, se estima del orden de 1 a 3 horas en total para ambos modelos — variará según tu equipo. Puedes correr esta sección de forma independiente (no depende de haber corrido nada más que la sección 1 de instalación y las definiciones de funciones de la sección 4-5).

### 14.1 Descarga de COCO val2017 (imágenes + anotaciones oficiales)

Descargamos el split de validación completo de COCO 2017: 5,000 imágenes con anotaciones completas de detección y segmentación (formato JSON original de COCO, no el formato YOLO que usa `coco128-seg`).

In [18]:
import shutil
from pathlib import Path
from ultralytics.utils.downloads import download

COCO_FULL_ROOT = Path("./dataset_coco_full")
COCO_FULL_ROOT.mkdir(exist_ok=True)

# Imágenes (≈1 GB, 5,000 imágenes)
download("http://images.cocodataset.org/zips/val2017.zip", dir=COCO_FULL_ROOT, unzip=True, delete=True)

# Anotaciones oficiales (≈241 MB; el zip trae train+val, solo usaremos instances_val2017.json)
download(
    "http://images.cocodataset.org/annotations/annotations_trainval2017.zip",
    dir=COCO_FULL_ROOT, unzip=True, delete=True,
)

FULL_IMAGES_DIR = COCO_FULL_ROOT / "val2017"
print(f"Imágenes descargadas: {len(list(FULL_IMAGES_DIR.glob('*.jpg')))}")

Downloading http://images.cocodataset.org/zips/val2017.zip to 'dataset_coco_full\val2017.zip': 100% ━━━━━━━━━━━━ 777.8MB 10.0MB/s 1:18 1:18<0.1sss
Unzipping dataset_coco_full\val2017.zip to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\val2017...: 100% ━━━━━━━━━━━━ 5001/5001 450.5files/s 11.1s0.0s
Downloading http://images.cocodataset.org/annotations/annotations_trainval2017.zip to 'dataset_coco_full\annotations_trainval2017.zip': 100% ━━━━━━━━━━━━ 241.2MB 9.6MB/s 25.1s 25.0s<0.1ss8
Unzipping dataset_coco_full\annotations_trainval2017.zip to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\annotations...: 100% ━━━━━━━━━━━━ 6/6 1.3files/s 4.5s0.7ss
Imágenes descargadas: 5000

### 14.2 Conversión de anotaciones: COCO JSON → formato YOLO

Usamos el conversor oficial de Ultralytics, que mapea automáticamente los 91 IDs de categoría originales de COCO a los 80 IDs que usan los pesos preentrenados (`cls91to80=True`), y extrae tanto los polígonos de segmentación como los bounding boxes.

In [19]:
from ultralytics.data.converter import convert_coco

# Aislamos solo el archivo de anotaciones de validación (evita procesar
# también instances_train2017.json, que son ~118,000 imágenes que no usaremos)
VAL_ANN_DIR = COCO_FULL_ROOT / "val_annotations_only"
VAL_ANN_DIR.mkdir(exist_ok=True)
shutil.copy(
    COCO_FULL_ROOT / "annotations" / "instances_val2017.json",
    VAL_ANN_DIR / "instances_val2017.json",
)

convert_coco(
    labels_dir=str(VAL_ANN_DIR),
    save_dir=str(COCO_FULL_ROOT / "yolo_labels"),
    use_segments=True,     # incluye polígonos de segmentación
    use_keypoints=False,
    cls91to80=True,        # mapea a los mismos 80 IDs que usan los pesos preentrenados
)

FULL_LABELS_DIR = COCO_FULL_ROOT / "yolo_labels" / "labels" / "val2017"
print(f"Labels generados: {len(list(FULL_LABELS_DIR.glob('*.txt')))}")

Annotations C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\val_annotations_only\instances_val2017.json: 100% ━━━━━━━━━━━━ 4952/4952 615.5it/s 8.0s0.1s
COCO data converted successfully.
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\yolo_labels
Labels generados: 4952

### 14.3 Partición 70/15/15 y generación de labels de detección

Mismo procedimiento que en la sección 3-4, aplicado ahora a las 5,000 imágenes.

In [20]:
random.seed(42)

FULL_SPLIT_ROOT = Path("./dataset_coco_full/split")
if FULL_SPLIT_ROOT.exists():
    shutil.rmtree(FULL_SPLIT_ROOT)

all_images_full = sorted(FULL_IMAGES_DIR.glob("*.jpg"))
random.shuffle(all_images_full)

n_total_full = len(all_images_full)
n_train_full = int(n_total_full * 0.70)
n_val_full = int(n_total_full * 0.15)
splits_full = {
    "train": all_images_full[:n_train_full],
    "val": all_images_full[n_train_full:n_train_full + n_val_full],
    "test": all_images_full[n_train_full + n_val_full:],
}

for split_name, img_list in splits_full.items():
    img_out = FULL_SPLIT_ROOT / "images" / split_name
    lbl_out = FULL_SPLIT_ROOT / "labels" / split_name
    img_out.mkdir(parents=True, exist_ok=True)
    lbl_out.mkdir(parents=True, exist_ok=True)
    for img_path in img_list:
        label_path = FULL_LABELS_DIR / (img_path.stem + ".txt")
        shutil.copy(img_path, img_out / img_path.name)
        if label_path.exists():
            shutil.copy(label_path, lbl_out / label_path.name)

for split_name, img_list in splits_full.items():
    pct = len(img_list) / n_total_full * 100
    print(f"  {split_name:5s}: {len(img_list):5d} imágenes ({pct:.1f}%)")

# Generamos labels de detección (bbox) a partir de los de segmentación,
# reutilizando la misma función definida en la sección 4
for split_name in ["train", "val", "test"]:
    seg_dir = FULL_SPLIT_ROOT / "labels" / split_name
    det_dir = FULL_SPLIT_ROOT / "labels_det" / split_name
    build_detection_labels(seg_dir, det_dir)

  train:  3500 imágenes (70.0%)
  val  :   750 imágenes (15.0%)
  test :   750 imágenes (15.0%)

### 14.4 Archivos de configuración (data.yaml)

In [21]:
def make_task_root_full(task_labels_dirname, task_root_name):
    task_root = Path(f"./dataset_coco_full/{task_root_name}")
    for split_name in ["train", "val", "test"]:
        img_src = (FULL_SPLIT_ROOT / "images" / split_name).resolve()
        lbl_src = (FULL_SPLIT_ROOT / task_labels_dirname / split_name).resolve()
        img_dst = task_root / "images" / split_name
        lbl_dst = task_root / "labels" / split_name
        img_dst.parent.mkdir(parents=True, exist_ok=True)
        lbl_dst.parent.mkdir(parents=True, exist_ok=True)
        if img_dst.exists() or img_dst.is_symlink():
            img_dst.unlink()
        if lbl_dst.exists() or lbl_dst.is_symlink():
            lbl_dst.unlink()
        img_dst.symlink_to(img_src)
        lbl_dst.symlink_to(lbl_src)
    return task_root

DET_ROOT_FULL = make_task_root_full("labels_det", "det_task_full")
SEG_ROOT_FULL = make_task_root_full("labels", "seg_task_full")

write_task_yaml("coco_det_full.yaml", DET_ROOT_FULL)
write_task_yaml("coco_seg_full.yaml", SEG_ROOT_FULL)
print("coco_det_full.yaml y coco_seg_full.yaml generados.")

coco_det_full.yaml y coco_seg_full.yaml generados.

### 14.5 Transfer learning con `yolov8m` — detección (80 épocas)

`workers=12` para aprovechar tus 16 núcleos de CPU en la carga de datos. `patience=15` detiene el entrenamiento automáticamente si no hay mejora en 15 épocas.

**Limpieza de memoria GPU** antes de cargar el siguiente modelo (evita acumulación de VRAM entre entrenamientos sucesivos).

In [22]:
import gc

# Liberamos memoria GPU/CPU acumulada de la etapa anterior antes de cargar
# el siguiente modelo. Evita el error 'CUDA out of memory' cuando se corren
# varios entrenamientos seguidos en la misma sesión de kernel.
torch.cuda.empty_cache()
gc.collect()
if torch.cuda.is_available():
    print(f"VRAM libre: {torch.cuda.mem_get_info()[0] / 1e9:.2f} GB de "
          f"{torch.cuda.mem_get_info()[1] / 1e9:.2f} GB totales")

In [23]:
model_det_full = YOLO("yolov8m.pt")

results_det_full = model_det_full.train(
    data="coco_det_full.yaml",
    epochs=80,
    imgsz=640,
    batch=8,
    device=DEVICE,
    workers=0,
    patience=40,
    project="runs_lab_full",
    name="coco_det_transfer_full",
    pretrained=True,
    exist_ok=True,
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8m.pt to 'yolov8m.pt': 100% ━━━━━━━━━━━━ 49.7MB 13.3MB/s 3.7s3.7s<0.1sss
Ultralytics 8.4.124  Python-3.11.13 torch-2.12.1+cpu CPU (Intel Core i7-9750H 2.60GHz)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco_det_full.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=80, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=coco_det_transfer_full, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=40, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_lab_full, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_full\coco_det_transfer_full, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=0, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3822016  ultralytics.nn.modules.head.Detect           [80, 16, None, [192, 384, 576]]
Model summary: 170 layers, 25,902,640 parameters, 25,902,624 gradients, 79.3 GFLOPs

Transferred 475/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
WARNING train: Slow image access detected (ping: 0.20.0 ms, read: 10.93.1 MB/s, size: 165.4 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\train... 3468 images, 32 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3500/3500 379.1it/s 9.2s0.0s
train: New cache created: C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\train.cache
WARNING val: Slow image access detected (ping: 0.10.0 ms, read: 18.25.8 MB/s, size: 202.4 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\val... 745 images, 5 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 750/750 410.5it/s 1.8s0.1s
val: New cache created: C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Plotting labels to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_full\coco_det_transfer_full\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_full\coco_det_transfer_full
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/80         0G     0.9391      1.115        1.1         49        640: 100% ━━━━━━━━━━━━ 438/438 18.6s/it 2:15:5115.6s09
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 47/47 9.5s/it 7:289.0sss
                   all        750       5105      0.668       0.62      0.651      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/80         0G     0.9526      1.146      1.115         76        640: 100% ━━━━━━━━━━━━ 438/438 18.8s/it 2:17:0316.1s13
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 47/47 9.3s/it 7:188.7sss
                   all        750       5105       0.67      0.561      0.609      0.445

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/80         0G     0.9659       1.18      1.125         55        640: 100% ━━━━━━━━━━━━ 438/438 18.4s/it 2:14:3711.7s21
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 47/47 7.9s/it 6:097.3ss
                   all        750       5105      0.606      0.559      0.576      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/80         0G     0.9729      1.159      1.128        125        640: 49% ━━━━━╸────── 216/438 19.4s/it 58:46<1:11:55

KeyboardInterrupt:

### 14.6 Transfer learning con `yolov8m-seg` — segmentación (80 épocas)

**Limpieza de memoria GPU** antes de cargar el siguiente modelo (evita acumulación de VRAM entre entrenamientos sucesivos).

In [24]:
import gc

# Liberamos memoria GPU/CPU acumulada de la etapa anterior antes de cargar
# el siguiente modelo. Evita el error 'CUDA out of memory' cuando se corren
# varios entrenamientos seguidos en la misma sesión de kernel.
torch.cuda.empty_cache()
gc.collect()
if torch.cuda.is_available():
    print(f"VRAM libre: {torch.cuda.mem_get_info()[0] / 1e9:.2f} GB de "
          f"{torch.cuda.mem_get_info()[1] / 1e9:.2f} GB totales")

In [5]:
from pathlib import Path
import pandas as pd

det_run = Path(
    "runs/detect/runs_lab_full/coco_det_transfer_full"
)

results_path = det_run / "results.csv"
last_path = det_run / "weights" / "last.pt"
best_path = det_run / "weights" / "best.pt"

history = pd.read_csv(results_path)

# Eliminar espacios que Ultralytics puede colocar en los encabezados
history.columns = history.columns.str.strip()

print("Épocas registradas:", len(history))
print("Última época registrada:", history["epoch"].iloc[-1])

print("\nCheckpoint para continuar:")
print(last_path.resolve())

print("\nCheckpoint con el mejor resultado:")
print(best_path.resolve())

print("\nÚltimas filas del entrenamiento:")
display(history.tail())

Épocas registradas: 3
Última época registrada: 3

Checkpoint para continuar:
C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_full\coco_det_transfer_full\weights\last.pt

Checkpoint con el mejor resultado:
C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_full\coco_det_transfer_full\weights\best.pt

Últimas filas del entrenamiento:

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
0,1,8598.48,0.93915,1.11482,1.09972,0.66806,0.62022,0.65060,0.48555,0.94768,0.97410,1.08474,0.000040,0.000040,0.000040
1,2,17262.40,0.95265,1.14641,1.11493,0.66997,0.56106,0.60882,0.44470,0.99549,1.08439,1.13731,0.000078,0.000078,0.000078
2,3,25710.70,0.96591,1.17987,1.12533,0.60576,0.55917,0.57601,0.42165,1.01770,1.16902,1.14273,0.000116,0.000116,0.000116

In [ ]:
""""
import gc
import torch
from ultralytics import YOLO

# Eliminar el checkpoint cargado en RAM
if "checkpoint" in globals():
    del checkpoint

gc.collect()
torch.cuda.empty_cache()

model_det_full = YOLO(str(cuda_checkpoint))

results_det_full = model_det_full.train(
    resume=True,
    device=0,
    batch=1,
    workers=2,
    amp=True,
    deterministic=False,
) """"

### 14.7 Evaluación en test (dataset completo)

In [1]:
""""
model_seg_full = YOLO("yolov8m-seg.pt")

results_seg_full = model_seg_full.train(
    data="coco_seg_full.yaml",
    epochs=80,
    imgsz=640,
    batch=8,
    device=DEVICE,
    workers=0,
    patience=40,
    project="runs_lab_full",
    name="coco_seg_transfer_full",
    pretrained=True,
    exist_ok=True,
)
"""""

import torch
from ultralytics import YOLO

DEVICE = 0

model_det_quick = YOLO("yolov8n.pt")

results_det_quick = model_det_quick.train(
    data="coco_det_full.yaml",

    epochs=3,
    imgsz=320,
    batch=4,

    device=DEVICE,
    workers=2,
    amp=True,
    deterministic=False,

    patience=2,
    val=True,
    plots=True,

    project="runs_lab_quick",
    name="coco_det_quick",
    exist_ok=True,
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 7.5MB/s 0.8s.7s<0.2s.4s
Ultralytics 8.4.124  Python-3.11.13 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 3072MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco_det_full.yaml, degrees=0.0, deterministic=False, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=3, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=320, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=coco_det_quick, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=2, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_lab_quick, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,157,200 parameters, 3,157,184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.0 ms, read: 711.1257.4 MB/s, size: 139.3 KB)
train: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\train.cache... 3468 images, 32 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3500/3500  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 629.7175.5 MB/s, size: 161.8 KB)
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\val.cache... 745 images, 5 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 750/750  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick\labels.jpg...
Image sizes 320 train, 320 val
Using 2 dataloader workers
Logging results to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/3      0.27G      1.428      2.333      1.264         64        320: 100% ━━━━━━━━━━━━ 875/875 8.7it/s 1:410.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 10.6it/s 8.9s0.2s
                   all        750       5105      0.538      0.367      0.383      0.261

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        2/3     0.289G      1.385      1.992      1.222         43        320: 100% ━━━━━━━━━━━━ 875/875 8.6it/s 1:410.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 11.8it/s 8.0s0.1s
                   all        750       5105      0.538      0.378      0.389      0.263

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        3/3     0.293G      1.369      1.918      1.211         65        320: 100% ━━━━━━━━━━━━ 875/875 8.5it/s 1:430.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 11.3it/s 8.3s0.1s
                   all        750       5105      0.551      0.374      0.398       0.27

3 epochs completed in 0.093 hours.
Optimizer stripped from C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick\weights\last.pt, 6.5MB
Optimizer stripped from C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick\weights\best.pt, 6.5MB

Validating C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick\weights\best.pt...
Ultralytics 8.4.124  Python-3.11.13 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 3072MiB)
Model summary (fused): 73 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 11.4it/s 8.2s0.2s
                   all        750       5105      0.549      0.376      0.399      0.271
                person        404       1518      0.785      0.472      0.569      0.359
               bicycle         19         43      0.516      0.256      0.274      0.127
                   car         81        267      0.706        0.3      0.347      0.198
            motorcycle         24         65      0.526      0.415       0.43      0.236
              airplane         14         15      0.835      0.867      0.918      0.742
                   bus         25         41      0.745        0.5      0.589      0.469
                 train         21         25      0.898       0.76      0.799      0.665
                 truck         32         56      0.579      0.295      0.373      0.215
                  boat         17         50      0.441       0.38      0.342      0.179
         traffic light         35        104      0.687      0.202      0.253      0.112
          fire hydrant          7          7      0.502      0.571      0.615      0.513
             stop sign         10         11      0.747      0.818      0.792      0.703
         parking meter          4         14      0.707      0.429      0.507      0.329
                 bench         38         61      0.589       0.23      0.277      0.173
                  bird         22         80      0.687      0.163      0.249      0.165
                   cat         23         26      0.768      0.808      0.852      0.674
                   dog         25         30      0.688      0.442      0.568      0.387
                 horse         17         52       0.54      0.587      0.589      0.379
                 sheep         11         54      0.549      0.463      0.457      0.321
                   cow         11         50      0.648       0.54      0.579      0.352
              elephant         14         46      0.544       0.63      0.605      0.421
                  bear         10         13      0.803      0.846      0.852      0.802
                 zebra         11         32       0.61      0.719      0.777      0.518
               giraffe         21         51      0.717      0.647      0.604      0.428
              backpack         42         60      0.295     0.0667     0.0702     0.0367
              umbrella         15         51      0.488      0.314       0.39      0.242
               handbag         34         61      0.579     0.0457     0.0566     0.0347
                   tie         19         26       0.55      0.308      0.359      0.212
              suitcase         14         51      0.641       0.35      0.421      0.284
               frisbee         11         12      0.691        0.5      0.665       0.51
                  skis         20         47      0.233      0.213      0.159     0.0915
             snowboard          8         13      0.243     0.0769     0.0353     0.0213
           sports ball         22         26      0.781      0.115       0.15      0.107
                  kite         10         20      0.384      0.375      0.372      0.178
          baseball bat         12         18      0.439      0.222      0.192     0.0587
        baseball glove         12         14      0.514      0.214      0.361      0.139
            skateboard         29         35      0.743      0.514      0.592      0.274
             surfboard         30         51      0.437      0.392      0.417      0.251
         tennis racket         31         38      0.436      0.474      0.482      0.241
                bottle         55        156      0.876      0.182      0.291      0.181
            wine glass         17         59      0.719      0.169      0.237      0.127
                   cup         50         85      0.395      0.212      0.188      0.133
                  fork         18         26      0.435      0.231      0.269      0.167
                 knife         27         51      0.303     0.0588       0.07     0.0405
                 spoon         24         44      0.453     0.0759      0.117     0.0676
                  bowl         37         89      0.503      0.213      0.292      0.202
                banana         11         31      0.317      0.226      0.277      0.172
                 apple          5         11          0          0    0.00101   0.000388
              sandwich         13         36      0.446      0.167      0.205       0.13
                orange         10         45      0.532        0.4      0.333      0.229
              broccoli         10         49       0.61      0.429        0.5      0.303
                carrot         11         37      0.454      0.189      0.157      0.106
               hot dog          2          2          0          0     0.0275      0.011
                 pizza         26         63      0.617      0.381      0.422      0.286
                 donut         10         54      0.345      0.278      0.298      0.191
                  cake         19         42      0.559      0.238      0.283      0.197
                 chair         83        229      0.569      0.162      0.226      0.131
                 couch         30         35      0.589        0.4      0.421      0.319
          potted plant         21         36      0.675      0.306      0.296      0.207
                   bed         28         34      0.731      0.618      0.556      0.393
          dining table         57         82      0.521      0.354       0.41      0.248
                toilet         23         35      0.565      0.657      0.579      0.435
                    tv         28         34      0.505      0.618       0.64      0.472
                laptop         26         40      0.532      0.483      0.496      0.342
                 mouse          9         12      0.738          1      0.851      0.568
                remote         17         47      0.322      0.106      0.127     0.0775
              keyboard         10         14      0.218      0.357      0.212      0.152
            cell phone         26         31      0.562      0.226       0.27      0.182
             microwave          7          7      0.517      0.616      0.647      0.435
                  oven         18         21      0.354      0.571      0.371      0.215
               toaster          2          2          1          0          0          0
                  sink         22         23      0.449      0.391      0.397      0.243
          refrigerator         17         25      0.573       0.52      0.595       0.44
                  book         40        178      0.464     0.0899      0.161     0.0567
                 clock         36         45        0.6      0.511      0.557      0.324
                  vase         19         33      0.643      0.333      0.403      0.333
              scissors          3          3      0.441      0.667      0.665      0.566
            teddy bear         12         16      0.715      0.688      0.637       0.51
            toothbrush          6          9       0.24     0.0532     0.0643     0.0432
Speed: 0.2ms preprocess, 3.3ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick

In [2]:
import gc
import torch
from ultralytics import YOLO

gc.collect()
torch.cuda.empty_cache()

model_seg_quick = YOLO("yolov8n-seg.pt")

results_seg_quick = model_seg_quick.train(
    data="coco_seg_full.yaml",
    epochs=3,
    imgsz=320,
    batch=4,
    device=0,
    workers=2,
    amp=True,
    deterministic=False,
    patience=2,
    val=True,
    plots=True,
    project="runs_lab_quick",
    name="coco_seg_quick",
    exist_ok=True,
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n-seg.pt to 'yolov8n-seg.pt': 100% ━━━━━━━━━━━━ 6.7MB 8.5MB/s 0.8s0.7s<0.1s1s
Ultralytics 8.4.124  Python-3.11.13 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 3072MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco_seg_full.yaml, degrees=0.0, deterministic=False, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=3, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=320, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=coco_seg_quick, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=2, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=runs_lab_quick, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1   1150432  ultralytics.nn.modules.head.Segment          [80, 32, 64, 16, None, [64, 128, 256]]
YOLOv8n-seg summary: 152 layers, 3,409,968 parameters, 3,409,952 gradients, 12.1 GFLOPs

Transferred 417/417 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.1 ms, read: 519.6178.7 MB/s, size: 165.4 KB)
train: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\train.cache... 3468 images, 32 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 3500/3500  0.0s
val: Fast image access  (ping: 0.10.0 ms, read: 827.3199.0 MB/s, size: 202.4 KB)
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco_full\split\labels\val.cache... 745 images, 5 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 750/750  0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Plotting labels to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick\labels.jpg...
Image sizes 320 train, 320 val
Using 2 dataloader workers
Logging results to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
        1/3     0.398G      1.425      3.272      2.231      1.247          0         64        320: 100% ━━━━━━━━━━━━ 875/875 6.7it/s 2:110.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 7.4it/s 12.7s0.1s
                   all        750       5105      0.552      0.353      0.382      0.263      0.555      0.337      0.359      0.221

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
        2/3     0.416G      1.395      3.177      1.998      1.216          0         43        320: 100% ━━━━━━━━━━━━ 875/875 6.7it/s 2:110.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 7.4it/s 12.7s0.1s
                   all        750       5105      0.522      0.371      0.377       0.26      0.619      0.332      0.359      0.218

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
        3/3     0.441G      1.381      3.138      1.937       1.21          0         65        320: 100% ━━━━━━━━━━━━ 875/875 6.7it/s 2:110.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 7.4it/s 12.7s0.1s
                   all        750       5105      0.553      0.368      0.383      0.263       0.59      0.342      0.364      0.219
EarlyStopping: Training stopped early as no improvement observed in last 2 epochs. Best results observed at epoch 1, best model saved as best.pt.
To update EarlyStopping(patience=2) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

3 epochs completed in 0.121 hours.
Optimizer stripped from C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick\weights\last.pt, 7.0MB
Optimizer stripped from C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick\weights\best.pt, 7.0MB

Validating C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick\weights\best.pt...
Ultralytics 8.4.124  Python-3.11.13 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 3072MiB)
YOLOv8n-seg summary (fused): 86 layers, 3,404,320 parameters, 0 gradients, 12.0 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 94/94 6.9it/s 13.7s0.1s
                   all        750       5105      0.554      0.354      0.382      0.263      0.552      0.338       0.36      0.221
                person        404       1518      0.819      0.429      0.551      0.347      0.818      0.407      0.522      0.269
               bicycle         19         43      0.239      0.233      0.246      0.126      0.149       0.14      0.136     0.0325
                   car         81        267      0.792      0.214      0.344      0.188      0.845       0.21      0.303      0.144
            motorcycle         24         65      0.517      0.362       0.39       0.24      0.495      0.338      0.349      0.151
              airplane         14         15      0.666        0.8      0.832       0.69      0.694        0.8      0.777        0.5
                   bus         25         41      0.535      0.488      0.516      0.451       0.57      0.488      0.517      0.417
                 train         21         25      0.882       0.76       0.79      0.657      0.906       0.76      0.796      0.616
                 truck         32         56      0.549      0.261      0.281      0.146      0.543      0.233      0.262      0.151
                  boat         17         50       0.39        0.3      0.242      0.114      0.383      0.286      0.252      0.103
         traffic light         35        104      0.641       0.12      0.184     0.0991      0.529     0.0972      0.149     0.0674
          fire hydrant          7          7      0.639      0.571      0.595      0.482      0.652      0.571      0.595      0.487
             stop sign         10         11      0.884      0.636      0.755      0.668      0.889      0.636      0.755      0.654
         parking meter          4         14      0.716        0.5      0.507      0.392      0.721        0.5      0.503      0.344
                 bench         38         61       0.93      0.219      0.293      0.176      0.796       0.18      0.232      0.117
                  bird         22         80      0.809      0.175      0.242      0.158      0.875      0.175      0.222      0.129
                   cat         23         26      0.697      0.769      0.826      0.665      0.684      0.692      0.726      0.562
                   dog         25         30      0.735      0.371      0.533      0.375      0.675      0.277      0.533      0.355
                 horse         17         52      0.635      0.538      0.572      0.361      0.665        0.5      0.508      0.237
                 sheep         11         54      0.636      0.481      0.486      0.335      0.646      0.481        0.5      0.292
                   cow         11         50      0.612       0.64      0.657      0.404      0.629       0.62      0.608      0.325
              elephant         14         46      0.485      0.543      0.584      0.448       0.52      0.565      0.598      0.398
                  bear         10         13      0.717      0.846      0.826      0.761      0.731      0.846      0.826      0.726
                 zebra         11         32       0.68      0.688      0.774      0.509      0.691      0.688      0.759      0.414
               giraffe         21         51      0.561      0.588      0.553      0.368      0.529      0.529      0.531      0.259
              backpack         42         60      0.362     0.0167     0.0485     0.0236      0.385     0.0167     0.0482      0.021
              umbrella         15         51      0.761      0.313       0.41      0.259      0.784      0.314       0.38      0.245
               handbag         34         61      0.913     0.0328     0.0666      0.026          1     0.0308     0.0809     0.0371
                   tie         19         26      0.647      0.352      0.369       0.21      0.667      0.346      0.395      0.208
              suitcase         14         51       0.88      0.216      0.387      0.258      0.918      0.218      0.404      0.233
               frisbee         11         12      0.937        0.5      0.666      0.478      0.954        0.5      0.651      0.444
                  skis         20         47      0.394      0.149      0.146     0.0741      0.303      0.106      0.114     0.0294
             snowboard          8         13          0          0     0.0147    0.00343          0          0     0.0136    0.00838
           sports ball         22         26      0.642      0.154      0.183      0.133      0.511      0.115      0.139     0.0923
                  kite         10         20      0.273       0.32      0.281      0.137      0.314       0.35      0.288      0.153
          baseball bat         12         18      0.366      0.167      0.189     0.0862      0.424      0.164      0.164     0.0803
        baseball glove         12         14      0.668      0.214      0.257      0.127      0.699      0.214      0.256       0.16
            skateboard         29         35       0.64      0.509      0.545      0.325      0.555      0.429      0.465      0.226
             surfboard         30         51      0.487      0.451      0.379      0.203      0.413      0.373      0.336      0.153
         tennis racket         31         38      0.556        0.5      0.446      0.209      0.614        0.5      0.462      0.302
                bottle         55        156      0.696      0.167      0.273      0.178       0.78       0.16      0.252      0.137
            wine glass         17         59      0.865      0.109      0.253      0.131       0.57     0.0678      0.139     0.0583
                   cup         50         85      0.468      0.259      0.209      0.141      0.433      0.212      0.162      0.109
                  fork         18         26      0.192      0.269      0.225      0.143       0.18      0.231       0.15     0.0768
                 knife         27         51      0.271      0.118     0.0875     0.0557      0.298      0.118      0.068       0.02
                 spoon         24         44      0.198     0.0455     0.0586     0.0395      0.206     0.0455     0.0542     0.0297
                  bowl         37         89      0.446      0.191      0.244      0.166      0.402      0.157      0.175      0.089
                banana         11         31      0.396      0.297      0.246      0.189      0.423       0.29      0.245      0.147
                 apple          5         11          0          0    0.00528    0.00422       0.23     0.0909     0.0317    0.00317
              sandwich         13         36      0.506      0.167      0.149     0.0991      0.515      0.167      0.141      0.104
                orange         10         45      0.462      0.248      0.228      0.157      0.463       0.23      0.225      0.144
              broccoli         10         49       0.56      0.408      0.539      0.261      0.604      0.408      0.512      0.242
                carrot         11         37      0.348      0.216      0.149      0.106      0.428      0.216      0.146     0.0933
               hot dog          2          2          0          0    0.00536    0.00228          0          0          0          0
                 pizza         26         63      0.458      0.524      0.444      0.297      0.472      0.508      0.432       0.25
                 donut         10         54      0.782        0.2      0.279      0.184      0.735      0.185      0.254      0.169
                  cake         19         42      0.594      0.238      0.272      0.187      0.613      0.226       0.26      0.183
                 chair         83        229      0.507      0.153      0.188      0.118      0.545      0.148      0.178     0.0835
                 couch         30         35      0.675      0.371      0.489      0.376      0.654      0.343      0.432      0.277
          potted plant         21         36      0.314     0.0556      0.149      0.107      0.341     0.0556      0.135     0.0741
                   bed         28         34      0.561        0.5      0.505      0.362      0.506      0.441       0.42      0.239
          dining table         57         82      0.484       0.28      0.345      0.195      0.312      0.177      0.116     0.0428
                toilet         23         35      0.624      0.571      0.548      0.416      0.666      0.571      0.572      0.351
                    tv         28         34      0.675      0.735      0.766      0.554      0.668      0.711      0.766      0.502
                laptop         26         40      0.532      0.375      0.431      0.304      0.535       0.35      0.342      0.186
                 mouse          9         12      0.848      0.917      0.957      0.677      0.854      0.917      0.957      0.547
                remote         17         47      0.452      0.128      0.146     0.0946      0.509      0.128      0.155     0.0716
              keyboard         10         14      0.156      0.429      0.352        0.2       0.19        0.5      0.376      0.225
            cell phone         26         31       0.55      0.258      0.254      0.184      0.554      0.241      0.241      0.177
             microwave          7          7      0.431      0.857      0.727      0.566      0.436      0.857      0.727      0.455
                  oven         18         21      0.391      0.429      0.423      0.272      0.354      0.333      0.394      0.233
               toaster          2          2          1          0          0          0          1          0          0          0
                  sink         22         23       0.42      0.391      0.405      0.229       0.39      0.348      0.372      0.251
          refrigerator         17         25      0.435       0.56      0.518      0.372      0.518        0.6      0.552       0.34
                  book         40        178      0.403     0.0618      0.127     0.0501      0.287     0.0393     0.0575     0.0149
                 clock         36         45        0.7      0.556      0.558      0.335      0.705      0.556      0.563      0.325
                  vase         19         33      0.873      0.364      0.434      0.362      0.887      0.364      0.428      0.314
              scissors          3          3      0.414      0.667      0.665      0.466      0.419      0.667      0.665        0.4
            teddy bear         12         16      0.762      0.402      0.577      0.468       0.75      0.375      0.569      0.373
            toothbrush          6          9          0          0     0.0132    0.00954          0          0    0.00344   0.000801
Speed: 0.2ms preprocess, 4.1ms inference, 0.0ms loss, 4.2ms postprocess per image
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick

In [5]:
"""""
metrics_det_full = model_det_full.val(data="coco_det_full.yaml", split="test", device=DEVICE)
metrics_seg_full = model_seg_full.val(data="coco_seg_full.yaml", split="test", device=DEVICE)

f1_det_full = (
    2 * metrics_det_full.box.mp * metrics_det_full.box.mr
    / (metrics_det_full.box.mp + metrics_det_full.box.mr)
    if (metrics_det_full.box.mp + metrics_det_full.box.mr) > 0 else 0.0
)

summary_full = pd.DataFrame({
    "Métrica": [
        "Precision (det)", "Recall (det)", "F1-score (det)",
        "mAP@0.50 (det)", "mAP@0.50:0.95 (det)",
        "Mask Precision", "Mask Recall",
        "Mask mAP@0.50", "Mask mAP@0.50:0.95",
    ],
    "Valor (128 imgs, yolov8s)": [
        precision_det, recall_det, f1_det, map50_det, map5095_det,
        mask_precision, mask_recall, mask_map50, mask_map5095,
    ],
    "Valor (5000 imgs, yolov8m)": [
        metrics_det_full.box.mp, metrics_det_full.box.mr, f1_det_full,
        metrics_det_full.box.map50, metrics_det_full.box.map,
        metrics_seg_full.seg.mp, metrics_seg_full.seg.mr,
        metrics_seg_full.seg.map50, metrics_seg_full.seg.map,
    ],
})
summary_full.iloc[:, 1:] = summary_full.iloc[:, 1:].round(4)
summary_full
"""""

import pandas as pd
from pathlib import Path
from ultralytics import YOLO

DEVICE = 0

# ============================================================
# 1. EXPERIMENTO DE 128 IMÁGENES CON YOLOv8s
# ============================================================

det_128_path = Path(
    "runs/detect/runs_lab/"
    "coco_det_transfer/weights/best.pt"
)

seg_128_path = Path(
    "runs/segment/runs_lab/"
    "coco_seg_transfer/weights/best.pt"
)

model_det_128 = YOLO(str(det_128_path))
model_seg_128 = YOLO(str(seg_128_path))

metrics_det_128 = model_det_128.val(
    data="coco_det.yaml",
    split="test",
    imgsz=640,
    batch=4,
    device=DEVICE,
    workers=2,
)

metrics_seg_128 = model_seg_128.val(
    data="coco_seg.yaml",
    split="test",
    imgsz=640,
    batch=4,
    device=DEVICE,
    workers=2,
)

# Variables que solicitaba la celda original
precision_det = metrics_det_128.box.mp
recall_det = metrics_det_128.box.mr

f1_det = (
    2 * precision_det * recall_det
    / (precision_det + recall_det)
    if (precision_det + recall_det) > 0
    else 0.0
)

map50_det = metrics_det_128.box.map50
map5095_det = metrics_det_128.box.map

mask_precision = metrics_seg_128.seg.mp
mask_recall = metrics_seg_128.seg.mr
mask_map50 = metrics_seg_128.seg.map50
mask_map5095 = metrics_seg_128.seg.map


# ============================================================
# 2. RESULTADOS RÁPIDOS DE 5000 IMÁGENES
# ============================================================

# Solo repite la evaluación si las variables se perdieron
if "metrics_det_quick" not in globals():
    model_det_quick = YOLO(
        "runs/detect/runs_lab_quick/"
        "coco_det_quick/weights/best.pt"
    )

    metrics_det_quick = model_det_quick.val(
        data="coco_det_full.yaml",
        split="test",
        imgsz=320,
        batch=4,
        device=DEVICE,
        workers=2,
    )

if "metrics_seg_quick" not in globals():
    model_seg_quick = YOLO(
        "runs/segment/runs_lab_quick/"
        "coco_seg_quick/weights/best.pt"
    )

    metrics_seg_quick = model_seg_quick.val(
        data="coco_seg_full.yaml",
        split="test",
        imgsz=320,
        batch=4,
        device=DEVICE,
        workers=2,
    )

precision_quick = metrics_det_quick.box.mp
recall_quick = metrics_det_quick.box.mr

f1_det_quick = (
    2 * precision_quick * recall_quick
    / (precision_quick + recall_quick)
    if (precision_quick + recall_quick) > 0
    else 0.0
)


# ============================================================
# 3. TABLA COMPARATIVA
# ============================================================

summary_full = pd.DataFrame({
    "Métrica": [
        "Precision (det)",
        "Recall (det)",
        "F1-score (det)",
        "mAP@0.50 (det)",
        "mAP@0.50:0.95 (det)",
        "Mask Precision",
        "Mask Recall",
        "Mask mAP@0.50",
        "Mask mAP@0.50:0.95",
    ],

    "Valor (128 imgs, yolov8s, 640px)": [
        precision_det,
        recall_det,
        f1_det,
        map50_det,
        map5095_det,
        mask_precision,
        mask_recall,
        mask_map50,
        mask_map5095,
    ],

    "Valor (5000 imgs, yolov8n, 320px, 3 épocas)": [
        metrics_det_quick.box.mp,
        metrics_det_quick.box.mr,
        f1_det_quick,
        metrics_det_quick.box.map50,
        metrics_det_quick.box.map,
        metrics_seg_quick.seg.mp,
        metrics_seg_quick.seg.mr,
        metrics_seg_quick.seg.map50,
        metrics_seg_quick.seg.map,
    ],
})

summary_full.iloc[:, 1:] = (
    summary_full.iloc[:, 1:]
    .astype(float)
    .round(4)
)

summary_full

Ultralytics 8.4.124  Python-3.11.13 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 3072MiB)
Model summary (fused): 73 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs
val: Fast image access  (ping: 0.20.0 ms, read: 111.315.0 MB/s, size: 49.6 KB)
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\test.cache... 20 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 20/20  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.2it/s 4.1s0.3s6s
                   all         20        106      0.709      0.753      0.847      0.674
                person          9         27      0.987      0.667      0.916      0.665
               bicycle          1          2      0.831        0.5      0.638      0.268
                   car          2          4      0.319       0.25      0.501      0.236
            motorcycle          1          2      0.814          1      0.995      0.795
                   bus          1          1      0.529          1      0.995      0.895
                 train          1          1      0.783          1      0.995      0.895
             stop sign          1          1      0.709          1      0.995      0.796
                  bird          1          8      0.794      0.966      0.955      0.743
                   cat          1          1      0.695          1      0.995      0.895
                   dog          1          1      0.495          1      0.995      0.895
              elephant          1          7      0.939          1      0.995      0.852
                 zebra          1          1      0.691          1      0.995      0.995
              umbrella          1          1      0.701          1      0.995      0.895
               frisbee          3          3       0.67          1      0.913      0.805
           sports ball          1          1          1          0          0          0
          baseball bat          1          1          0          0      0.199     0.0873
        baseball glove          1          1      0.685          1      0.995      0.895
            skateboard          1          3          1          0      0.626      0.243
         tennis racket          1          1       0.47          1      0.497      0.199
                bottle          2          3      0.597      0.667      0.585      0.556
                   cup          1          2      0.781          1      0.995      0.995
                 knife          1          5      0.889          1      0.995      0.867
                 spoon          1          1      0.632          1      0.995      0.398
                  bowl          1          1        0.4          1      0.497      0.448
                banana          1          1      0.651          1      0.995      0.995
              sandwich          1          1          1          0      0.995      0.895
                   bed          1          1      0.886          1      0.995      0.448
          dining table          2          2          1      0.974      0.995      0.671
                    tv          1          1      0.648          1      0.995      0.895
                 mouse          1          1          1          0      0.995      0.697
             microwave          1          1      0.709          1      0.995      0.895
                  oven          1          1      0.424          1      0.995      0.995
                  book          2         16      0.363     0.0625      0.585      0.262
            teddy bear          1          2          1        0.5      0.995      0.846
Speed: 4.4ms preprocess, 29.4ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\val-3
Ultralytics 8.4.124  Python-3.11.13 torch-2.7.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1050, 3072MiB)
YOLOv8s-seg summary (fused): 86 layers, 11,810,560 parameters, 0 gradients, 40.1 GFLOPs
val: Fast image access  (ping: 0.10.0 ms, read: 557.6135.4 MB/s, size: 77.4 KB)
val: Scanning C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\dataset_coco\split\labels\test.cache... 20 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 20/20  0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.1s/it 5.4s0.5s1s
                   all         20        106      0.703      0.758      0.847      0.688      0.703      0.758      0.833       0.59
                person          9         27          1      0.689      0.893      0.636          1      0.689      0.895      0.475
               bicycle          1          2          1      0.991      0.995      0.546          1      0.991      0.995        0.4
                   car          2          4      0.527       0.25      0.444      0.254      0.527       0.25      0.444      0.256
            motorcycle          1          2      0.816          1      0.995      0.795      0.816          1      0.995      0.546
                   bus          1          1      0.723          1      0.995      0.895      0.723          1      0.995      0.895
                 train          1          1      0.725          1      0.995      0.895      0.725          1      0.995      0.895
             stop sign          1          1      0.726          1      0.995      0.796      0.726          1      0.995      0.697
                  bird          1          8      0.937          1      0.995      0.738      0.937          1      0.995      0.632
                   cat          1          1      0.721          1      0.995      0.895      0.721          1      0.995      0.895
                   dog          1          1       0.62          1      0.995      0.995       0.62          1      0.995      0.895
              elephant          1          7      0.938          1      0.995      0.866      0.938          1      0.995      0.688
                 zebra          1          1      0.719          1      0.995      0.995      0.719          1      0.995      0.895
              umbrella          1          1      0.755          1      0.995      0.895      0.755          1      0.995      0.895
               frisbee          3          3      0.734          1      0.913       0.83      0.734          1      0.913       0.64
           sports ball          1          1          1          0          0          0          1          0          0          0
          baseball bat          1          1          0          0     0.0905     0.0543          0          0     0.0905     0.0362
        baseball glove          1          1      0.432          1      0.995      0.895      0.432          1      0.995      0.895
            skateboard          1          3      0.233      0.155      0.443      0.178      0.233      0.155      0.168     0.0854
         tennis racket          1          1      0.817          1      0.995      0.398      0.817          1      0.995      0.431
                bottle          2          3       0.62      0.667      0.753      0.733       0.62      0.667      0.753      0.649
                   cup          1          2      0.688          1      0.995      0.995      0.688          1      0.995      0.945
                 knife          1          5      0.865          1      0.995       0.87      0.865          1      0.995      0.721
                 spoon          1          1      0.662          1      0.995      0.895      0.662          1      0.995      0.895
                  bowl          1          1      0.746          1      0.995      0.895      0.746          1      0.995      0.697
                banana          1          1      0.735          1      0.995      0.895      0.735          1      0.995      0.697
              sandwich          1          1      0.905          1      0.995      0.895      0.905          1      0.995      0.497
                   bed          1          1          1          0      0.995      0.448          1          0      0.995      0.448
          dining table          2          2      0.558        0.5      0.662      0.553      0.558        0.5      0.662      0.446
                    tv          1          1      0.666          1      0.995      0.895      0.666          1      0.995      0.895
                 mouse          1          1          1          0      0.497      0.398          1          0      0.497      0.298
             microwave          1          1      0.473          1      0.995      0.497      0.473          1      0.995      0.298
                  oven          1          1      0.578          1      0.995      0.995      0.578          1      0.995      0.895
                  book          2         16     0.0564    0.00705      0.476      0.269     0.0564    0.00705       0.26      0.132
            teddy bear          1          2      0.942        0.5      0.745      0.596      0.942        0.5      0.745      0.397
Speed: 5.9ms preprocess, 33.4ms inference, 0.0ms loss, 8.7ms postprocess per image
Results saved to C:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\val-3

,Métrica,"Valor (128 imgs, yolov8s, 640px)","Valor (5000 imgs, yolov8n, 320px, 3 épocas)"
0,Precision (det),0.7086,0.5776
1,Recall (det),0.7525,0.3752
2,F1-score (det),0.7299,0.4549
3,mAP@0.50 (det),0.8471,0.4027
4,mAP@0.50:0.95 (det),0.6742,0.2715
5,Mask Precision,0.7034,0.5189
6,Mask Recall,0.7576,0.3539
7,Mask mAP@0.50,0.8327,0.3605
8,Mask mAP@0.50:0.95,0.5902,0.2163

### Resultado principal: pérdida de generalización durante el ajuste fino 😳💥
Los modelos de detección y segmentación se ajustaron a partir de los pesos preentrenados `yolov8m.pt` y `yolov8m-seg.pt`, utilizando 5,000 imágenes provenientes de COCO val2017. Inicialmente, el entrenamiento se configuró con `patience=15`. Posteriormente, se incrementó este valor a `patience=40` para comprobar si el entrenamiento se estaba deteniendo antes de alcanzar un mejor desempeño.

Sin embargo, ampliar la paciencia no produjo una mejora. En ambos modelos, el checkpoint con los mejores resultados (`best.pt`) correspondió a la primera época. A partir de ese momento, ninguna de las épocas posteriores logró superar el rendimiento inicial y el entrenamiento terminó después de 41 épocas debido al criterio de parada temprana.

El análisis de las curvas permite observar dos comportamientos opuestos. Por un lado, las funciones de pérdida calculadas sobre el conjunto de entrenamiento, como `box_loss`, `cls_loss` y `seg_loss`, disminuyeron progresivamente. En el modelo de detección, por ejemplo, `box_loss` pasó de 0.938 en la primera época a 0.771 en la época 41. Por otro lado, el desempeño sobre los datos de validación se deterioró: el mAP@0.50 disminuyó de 0.651 a 0.525 en detección y de 0.633 a 0.527 en segmentación.

Este patrón es característico del sobreajuste. Aunque los modelos aprendieron a representar cada vez mejor las imágenes utilizadas durante el entrenamiento, su capacidad para responder correctamente ante datos no utilizados en la actualización de los pesos se redujo.

Una posible explicación se encuentra en la relación entre los datos de preentrenamiento y el subconjunto empleado para el fine-tuning. Los pesos originales de YOLOv8 fueron obtenidos mediante el entrenamiento con aproximadamente 118,000 imágenes de COCO train2017, un conjunto considerablemente más amplio y diverso que las 3,500 imágenes destinadas al entrenamiento en esta extensión. Además, ambos conjuntos pertenecen a la misma distribución general de COCO.

Por esta razón, los modelos ya contaban desde el inicio con representaciones suficientemente generales para resolver la tarea. Al continuar modificando sus parámetros con un subconjunto mucho más reducido, comenzaron a adaptarse excesivamente a las características particulares de esa partición. Como consecuencia, se alejaron de la solución general aprendida durante el preentrenamiento y disminuyeron su capacidad de generalización. El mejor resultado apareció en la época 1 porque, en ese momento, los pesos todavía conservaban gran parte de la información adquirida originalmente.

Este resultado difiere del observado en el laboratorio base con `coco128-seg`, donde se utilizaron únicamente 89 imágenes para el entrenamiento. En ese caso, el ajuste fino produjo beneficios durante las primeras épocas. Una explicación probable es que dicho conjunto presentaba una composición de clases más particular, incluyendo categorías con una o dos instancias, por lo que el modelo sí necesitaba adaptarse a esas condiciones específicas. En cambio, el subconjunto de 3,500 imágenes de val2017 conserva suficientemente bien las características generales de COCO, haciendo menos necesario un ajuste adicional de todos los parámetros.

### Conclusión obtenida del experimento 👽🔥

Los resultados muestran que aumentar el número de imágenes o utilizar una arquitectura de mayor capacidad no conduce automáticamente a un mejor desempeño. La efectividad del fine-tuning depende de la cantidad y diversidad de los datos disponibles, así como de su semejanza con la distribución utilizada durante el preentrenamiento.

Cuando el conjunto de ajuste es considerablemente menor que el conjunto original y ambos contienen información similar, una actualización intensa de los pesos puede perjudicar el rendimiento previamente adquirido. Para evitar este comportamiento, sería conveniente aplicar una tasa de aprendizaje más pequeña, mantener congeladas más capas del modelo o limitar el número de épocas. También resulta importante evaluar cuidadosamente el desempeño desde las primeras épocas, utilizando el resultado inicial como referencia para detectar oportunamente cualquier pérdida de generalización.

In [4]:
from pathlib import Path
import yaml

search_root = Path.cwd()

checkpoints = sorted(search_root.rglob("best.pt"))

print(f"Checkpoints encontrados: {len(checkpoints)}\n")

for index, checkpoint_path in enumerate(checkpoints):
    run_dir = checkpoint_path.parent.parent
    args_path = run_dir / "args.yaml"

    print(f"[{index}] {checkpoint_path}")

    if args_path.exists():
        with open(args_path, "r", encoding="utf-8") as file:
            args = yaml.safe_load(file)

        print("    task:", args.get("task"))
        print("    model:", args.get("model"))
        print("    data:", args.get("data"))
        print("    imgsz:", args.get("imgsz"))
        print("    epochs:", args.get("epochs"))
        print("    name:", args.get("name"))

    print()

Checkpoints encontrados: 5

[0] c:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab\coco_det_transfer\weights\best.pt
    task: detect
    model: yolov8s.pt
    data: coco_det.yaml
    imgsz: 640
    epochs: 30
    name: coco_det_transfer

[1] c:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_full\coco_det_transfer_full\weights\best.pt
    task: detect
    model: runs\detect\runs_lab_full\coco_det_transfer_full\weights\last_cuda.pt
    data: coco_det_full.yaml
    imgsz: 640
    epochs: 80
    name: coco_det_transfer_full

[2] c:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\detect\runs_lab_quick\coco_det_quick\weights\best.pt
    task: detect
    model: yolov8n.pt
    data: coco_det_full.yaml
    imgsz: 320
    epochs: 3
    name: coco_det_quick

[3] c:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab\coco_seg_transfer\weights\best.pt
    task: segment
    model: yolov8s-seg.pt
    data: coco_seg.yaml
    imgsz: 640
    epochs: 30
    name: coco_seg_transfer

[4] c:\Specialization_Artificial_Intelligence_Cinvestav\Module4_MarioValdovinos\runs\segment\runs_lab_quick\coco_seg_quick\weights\best.pt
    task: segment
    model: yolov8n-seg.pt
    data: coco_seg_full.yaml
    imgsz: 320
    epochs: 3
    name: coco_seg_quick